# This actually tells Travis to use the fast container-based test runner instead of the slow VM-based runner.
sudo: false

language: go

go:
  - 1.11.x

# Only clone the most recent commit.
git:
  depth: 1

# Make sure golangci-lint is vendored.
before_script:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
  - go test -v -race ./core
  - go test -v -race ./cmd
