schedules:
  - cron: "0 0 * * *"
    displayName: "Daily midnight build"
    branches:
      include:
        - master
    always: true

pool:
  vmImage: "Ubuntu-16.04"

variables:
  GOBIN: "$(GOPATH)/bin" # Go binaries path
  GOROOT: "/usr/local/go1.14.2" # Go installation path
  GOPATH: "$(system.defaultWorkingDirectory)/gopath" # Go workspace path
  modulePath: "$(GOPATH)/src/github.com/$(build.repository.name)" # Path to the module's code
  GO111MODULE: "on"
  linterTimeout: "5m"

steps:
  - task: GoTool@0
    inputs:
      version: '1.14.2'

  - task: Go@0
    inputs:
      command: 'get'
      arguments: '-d'
      workingDirectory: '$(System.DefaultWorkingDirectory)'

  - script: |
      HELM_URL=https://get.helm.sh
      HELM_TGZ=helm-v3.1.2-linux-amd64.tar.gz
      wget -q ${HELM_URL}/${HELM_TGZ}
      tar xzfv ${HELM_TGZ}
      PATH=`pwd`/linux-amd64/:$PATH
    displayName: "Install helm"

  - script: |
      curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.25.0
    displayName: Install linter

  - script: |
      golangci-lint run --timeout $(linterTimeout)
    workingDirectory: "$(modulePath)"
    displayName: "Lint"
 
 - task: Go@0
    inputs:
      command: 'build'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      
 - task: Go@0
    inputs:
    command: 'test'
    arguments: '-v', '-race'
    workingDirectory: '$(modulePath)'
      
  - task: CopyFiles@2
    inputs:
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: drop
